// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.0
// source: src/proto/messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "daw.protocol";

/** SPDX-License-Identifier: GPL-3.0-or-later */

/** Transport control */
export interface TransportCommand {
  action: TransportCommand_Action;
  /** Only used when action == SEEK (in samples) */
  seekPosition: number;
  /** Only used when action == LOOP */
  loopEnabled: boolean;
  /**
   * BOUCLE UTILISATEUR (AUDIT-6 QW, 2026-08-27) - action == LOOP :
   * set_region pose la region [loop_start, loop_end) en samples (le
   * wrap se fait sur elle) ; clear_region revient aux braces AUTO
   * [0, fin du contenu]. Sans l'un ni l'autre : simple toggle (la
   * region en place est conservee). Etat de PERFORMANCE, jamais CRDT.
   */
  setRegion: boolean;
  loopStart: number;
  loopEnd: number;
  clearRegion: boolean;
}

export enum TransportCommand_Action {
  PLAY = 0,
  STOP = 1,
  SEEK = 2,
  /** LOOP - V1.1: toggle looping (performance state, never CRDT) */
  LOOP = 3,
  UNRECOGNIZED = -1,
}

export function transportCommand_ActionFromJSON(object: any): TransportCommand_Action {
  switch (object) {
    case 0:
    case "PLAY":
      return TransportCommand_Action.PLAY;
    case 1:
    case "STOP":
      return TransportCommand_Action.STOP;
    case 2:
    case "SEEK":
      return TransportCommand_Action.SEEK;
    case 3:
    case "LOOP":
      return TransportCommand_Action.LOOP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransportCommand_Action.UNRECOGNIZED;
  }
}

export function transportCommand_ActionToJSON(object: TransportCommand_Action): string {
  switch (object) {
    case TransportCommand_Action.PLAY:
      return "PLAY";
    case TransportCommand_Action.STOP:
      return "STOP";
    case TransportCommand_Action.SEEK:
      return "SEEK";
    case TransportCommand_Action.LOOP:
      return "LOOP";
    case TransportCommand_Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Monitor control (solo/mute per track - local to this client) */
export interface SetMonitor {
  trackId: string;
  solo: boolean;
  mute: boolean;
}

/**
 * S8a: subscribe/unsubscribe this client to the master tap (the jam
 * road: engine -> LOCAL tab over loopback; the tab ships it P2P)
 */
export interface TapControl {
  enabled: boolean;
}

/**
 * Transport position (sent at 30 Hz)
 * Client -> Engine: open/close a plugin's native GUI window on demand.
 * Per-node toggle (the --editors flag only opened them ALL at spawn).
 */
export interface EditorControl {
  /** the chain node whose plugin window to toggle */
  nodeId: string;
  /** true = show the GUI, false = close it */
  open: boolean;
}

/**
 * F5 : Client -> Engine. Lancer / arreter un slot du clip-launcher (Session).
 * Les slots jouent en boucle sur l'horloge de session (independants du
 * transport d'arrangement). track_id vide = tous les pistes de la scene.
 * F5+ semantique du STOP : scene_id vide = arreter QUEL QUE SOIT le slot
 * (track_id vide en plus = STOP ALL) ; scene_id donne = n'arreter que les
 * slots DE CETTE SCENE (avant F5+, stop arretait tout - defaut corrige).
 */
export interface SessionLaunch {
  /** la scene (ligne) du slot a lancer */
  sceneId: string;
  /** la piste (colonne) ; vide = toute la scene */
  trackId: string;
  /** true = arreter (le slot de track_id, ou toute la scene) */
  stop: boolean;
  /**
   * F5+ : lancer au prochain QUANTUM au lieu d'immediatement. Le quantum =
   * loop_len du 1er slot lance (l'ancre, qui part immediatement et pose
   * l'epoque). Ignore quand rien ne joue (le lancement est l'ancre).
   */
  quantize: boolean;
}

/**
 * F5+ : Engine -> Client, avec la telemetrie. La VERITE des slots (l'UI
 * n'affiche plus un etat local optimiste) : un slot absent est arrete ;
 * queued = lance mais en attente de son quantum.
 */
export interface SessionState {
  slots: SessionState_Slot[];
}

export interface SessionState_Slot {
  trackId: string;
  sceneId: string;
  /** true = en file (quantize), false = joue */
  queued: boolean;
}

export interface TransportPosition {
  positionSamples: number;
  isPlaying: boolean;
  /**
   * AUDIT-5 A8: the engine's real device sample rate, so the web stops
   * hardcoding 48000 (the playhead drifts 8.8% on a 44.1k device).
   * Additive: 0 (absent, old engine) -> the web keeps its 48000 fallback.
   */
  sampleRate: number;
}

/** Per-track meter levels */
export interface TrackMeter {
  trackId: string;
  peakLeft: number;
  peakRight: number;
}

/** All meters (sent at 30 Hz) */
export interface Meters {
  tracks: TrackMeter[];
  /** V1.2: post-master-gain output peaks - */
  masterPeakLeft: number;
  /** the browser had NO master path before */
  masterPeakRight: number;
}

/** Engine state (sent at 30 Hz with telemetry) */
export interface EngineState {
  /** Cumulative underrun count */
  bufferUnderruns: number;
  /** Audio thread CPU usage (0-100) */
  cpuPercent: number;
  /** Current output latency */
  latencySamples: number;
  /** 2.4c-1: bridge blocks bypassed (child late/dead) */
  pluginBlocksMissed: number;
  /** c-2: false during a death window / permanent bypass */
  pluginChildAlive: boolean;
  /** c-2: cold restart attempts (budget 3) */
  pluginChildRestarts: number;
  /**
   * Garde de projet (2026-08-27, « onglet vide mais l'export sonne ») :
   * le PROJET que ce moteur joue. L'onglet compare a son ?project= et
   * AFFICHE le desaccord (bandeau + refus d'export) au lieu de laisser
   * deux verites coexister. Additif : vide (vieux moteur / mode fichier)
   * = pas de garde.
   */
  projectId: string;
  /**
   * LOT P (perf au regime de preuve, 2026-08-27) : le churn des stems
   * (compteur cumulatif de stems rendus - la question de la revue :
   * « le badge est-il perime 80 % du temps en edition active ? » se
   * chiffre avec ce compteur) et la VERITE du device (periode nego-
   * ciee + mode exclusif reellement obtenu, pas demande).
   */
  stemsRenderedTotal: number;
  devicePeriodFrames: number;
  deviceExclusive: boolean;
  /**
   * LE FUSIBLE (2026-08-29) : limiteur brick-wall de la sortie LIVE du
   * moteur (jamais dans les stems ni l'export). Reduction de gain du
   * dernier bloc (dB >= 0), blocs retenus cumules, plafond en vigueur.
   * L'UI l'affiche (badge LIM sur le master) : une action qui retient
   * le son se MONTRE, jamais en silence.
   */
  limiterReductionDb: number;
  limiterEngagedBlocks: number;
  limiterCeilingDb: number;
  limiterEnabled: boolean;
}

/**
 * S8a: a batch of post-master audio blocks for the subscribed tab.
 * first_seq counts 256-frame blocks since tap start; a seq gap = the
 * control thread fell behind and the ring dropped (counted, visible).
 * Samples are interleaved stereo float32, little-endian.
 */
export interface AudioTap {
  firstSeq: number;
  blockCount: number;
  /** block_count * 256 * 2 * 4 bytes */
  samples: Uint8Array;
  /** cumulative ring overruns */
  droppedBlocks: number;
}

/**
 * EXPORT MIXDOWN (AUDIT-6 quick win 1) : le client demande au moteur de
 * rendre le document COURANT hors ligne (meme noyau que --render) et de
 * publier le WAV au store d'assets. Le rendu tourne sur un thread ouvrier
 * dedie - jamais la boucle de controle (lecon C1), jamais le thread audio.
 */
export interface RenderRequest {
  /** 16 | 24 | 32 ; 0 = defaut (24) */
  bitDepth: number;
}

/**
 * Moteur -> Client : etat de l'export. STARTED a l'acceptation, puis DONE
 * (wav_hash = sha256 du WAV, disponible sur /assets/<hash> du serveur) ou
 * FAILED (error lisible). Un seul export a la fois : une demande pendant
 * un rendu repond FAILED sans toucher au rendu en cours.
 */
export interface RenderState {
  status: RenderState_Status;
  /** DONE : sha256 du WAV publie au store */
  wavHash: string;
  /** FAILED : la raison, lisible */
  error: string;
  /** DONE : frames rendues */
  lengthSamples: number;
  /** DONE : taux du rendu */
  sampleRate: number;
  /** DONE : profondeur du rendu */
  bitDepth: number;
}

export enum RenderState_Status {
  STARTED = 0,
  DONE = 1,
  FAILED = 2,
  UNRECOGNIZED = -1,
}

export function renderState_StatusFromJSON(object: any): RenderState_Status {
  switch (object) {
    case 0:
    case "STARTED":
      return RenderState_Status.STARTED;
    case 1:
    case "DONE":
      return RenderState_Status.DONE;
    case 2:
    case "FAILED":
      return RenderState_Status.FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RenderState_Status.UNRECOGNIZED;
  }
}

export function renderState_StatusToJSON(object: RenderState_Status): string {
  switch (object) {
    case RenderState_Status.STARTED:
      return "STARTED";
    case RenderState_Status.DONE:
      return "DONE";
    case RenderState_Status.FAILED:
      return "FAILED";
    case RenderState_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * LE MOTEUR SUIT L'ONGLET (2026-08-27, ratification utilisateur : « le
 * moteur est lock sur studio ») : le client demande au moteur de BASCULER
 * sur un autre projet du meme serveur. Le moteur : stop transport,
 * document neuf, reconnexion ServerClient sur le nouvel id, graphe
 * reconstruit a l'adoption. La verite de l'etat reste EngineState.
 * project_id (la garde d'onglet s'eteint d'elle-meme quand ca matche).
 * Geste EXPLICITE (bouton du bandeau) - jamais un auto-switch silencieux
 * (deux onglets sur deux projets se voleraient le moteur sans le dire).
 */
export interface SwitchProject {
  /** [A-Za-z0-9_-]{1,64}, valide par le moteur */
  projectId: string;
}

/** 2.5-decouverte: one scanned plugin class (Audio Module Class only) */
export interface PluginEntry {
  /** 32-hex VST3 class id */
  uid: string;
  name: string;
  vendor: string;
  /** e.g. "Fx|Dynamics|Stereo", "Instrument|Synth" */
  subCategories: string;
}

/**
 * The engine's plugin catalog: scanned from --vst3-dir folders (cache
 * by path+size+mtime, enumeration in the crash-isolated child), plus
 * explicit --vst3-module mappings. Sent ONCE per connection, on auth.
 */
export interface PluginCatalog {
  entries: PluginEntry[];
}

/** Error from engine */
export interface Error {
  severity: Error_Severity;
  /** Machine-readable error code */
  code: string;
  /** Human-readable message */
  message: string;
}

export enum Error_Severity {
  WARNING = 0,
  ERROR = 1,
  FATAL = 2,
  UNRECOGNIZED = -1,
}

export function error_SeverityFromJSON(object: any): Error_Severity {
  switch (object) {
    case 0:
    case "WARNING":
      return Error_Severity.WARNING;
    case 1:
    case "ERROR":
      return Error_Severity.ERROR;
    case 2:
    case "FATAL":
      return Error_Severity.FATAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Error_Severity.UNRECOGNIZED;
  }
}

export function error_SeverityToJSON(object: Error_Severity): string {
  switch (object) {
    case Error_Severity.WARNING:
      return "WARNING";
    case Error_Severity.ERROR:
      return "ERROR";
    case Error_Severity.FATAL:
      return "FATAL";
    case Error_Severity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Message {
  /** Client -> Engine */
  transport?: TransportCommand | undefined;
  setMonitor?:
    | SetMonitor
    | undefined;
  /** S8a */
  tapControl?:
    | TapControl
    | undefined;
  /** open/close a plugin GUI window */
  editor?:
    | EditorControl
    | undefined;
  /** F5 : lancer/arreter un slot Session */
  sessionLaunch?:
    | SessionLaunch
    | undefined;
  /** export mixdown (AUDIT-6 QW1) */
  renderRequest?:
    | RenderRequest
    | undefined;
  /** le moteur suit l'onglet */
  switchProject?:
    | SwitchProject
    | undefined;
  /** Engine -> Client */
  position?: TransportPosition | undefined;
  meters?: Meters | undefined;
  engineState?: EngineState | undefined;
  error?:
    | Error
    | undefined;
  /** S8a */
  audioTap?:
    | AudioTap
    | undefined;
  /** 2.5-decouverte */
  pluginCatalog?:
    | PluginCatalog
    | undefined;
  /** F5+ : verite des slots Session */
  sessionState?:
    | SessionState
    | undefined;
  /** etat de l'export mixdown */
  renderState?: RenderState | undefined;
}

function createBaseTransportCommand(): TransportCommand {
  return {
    action: 0,
    seekPosition: 0,
    loopEnabled: false,
    setRegion: false,
    loopStart: 0,
    loopEnd: 0,
    clearRegion: false,
  };
}

export const TransportCommand: MessageFns<TransportCommand> = {
  encode(message: TransportCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== 0) {
      writer.uint32(8).int32(message.action);
    }
    if (message.seekPosition !== 0) {
      writer.uint32(16).int64(message.seekPosition);
    }
    if (message.loopEnabled !== false) {
      writer.uint32(24).bool(message.loopEnabled);
    }
    if (message.setRegion !== false) {
      writer.uint32(32).bool(message.setRegion);
    }
    if (message.loopStart !== 0) {
      writer.uint32(40).int64(message.loopStart);
    }
    if (message.loopEnd !== 0) {
      writer.uint32(48).int64(message.loopEnd);
    }
    if (message.clearRegion !== false) {
      writer.uint32(56).bool(message.clearRegion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransportCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransportCommand();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.action = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.seekPosition = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.loopEnabled = reader.bool();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.setRegion = reader.bool();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.loopStart = longToNumber(reader.int64());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.loopEnd = longToNumber(reader.int64());
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.clearRegion = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransportCommand {
    return {
      action: isSet(object.action) ? transportCommand_ActionFromJSON(object.action) : 0,
      seekPosition: isSet(object.seekPosition)
        ? globalThis.Number(object.seekPosition)
        : isSet(object.seek_position)
        ? globalThis.Number(object.seek_position)
        : 0,
      loopEnabled: isSet(object.loopEnabled)
        ? globalThis.Boolean(object.loopEnabled)
        : isSet(object.loop_enabled)
        ? globalThis.Boolean(object.loop_enabled)
        : false,
      setRegion: isSet(object.setRegion)
        ? globalThis.Boolean(object.setRegion)
        : isSet(object.set_region)
        ? globalThis.Boolean(object.set_region)
        : false,
      loopStart: isSet(object.loopStart)
        ? globalThis.Number(object.loopStart)
        : isSet(object.loop_start)
        ? globalThis.Number(object.loop_start)
        : 0,
      loopEnd: isSet(object.loopEnd)
        ? globalThis.Number(object.loopEnd)
        : isSet(object.loop_end)
        ? globalThis.Number(object.loop_end)
        : 0,
      clearRegion: isSet(object.clearRegion)
        ? globalThis.Boolean(object.clearRegion)
        : isSet(object.clear_region)
        ? globalThis.Boolean(object.clear_region)
        : false,
    };
  },

  toJSON(message: TransportCommand): unknown {
    const obj: any = {};
    if (message.action !== 0) {
      obj.action = transportCommand_ActionToJSON(message.action);
    }
    if (message.seekPosition !== 0) {
      obj.seekPosition = Math.round(message.seekPosition);
    }
    if (message.loopEnabled !== false) {
      obj.loopEnabled = message.loopEnabled;
    }
    if (message.setRegion !== false) {
      obj.setRegion = message.setRegion;
    }
    if (message.loopStart !== 0) {
      obj.loopStart = Math.round(message.loopStart);
    }
    if (message.loopEnd !== 0) {
      obj.loopEnd = Math.round(message.loopEnd);
    }
    if (message.clearRegion !== false) {
      obj.clearRegion = message.clearRegion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransportCommand>, I>>(base?: I): TransportCommand {
    return TransportCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransportCommand>, I>>(object: I): TransportCommand {
    const message = createBaseTransportCommand();
    message.action = object.action ?? 0;
    message.seekPosition = object.seekPosition ?? 0;
    message.loopEnabled = object.loopEnabled ?? false;
    message.setRegion = object.setRegion ?? false;
    message.loopStart = object.loopStart ?? 0;
    message.loopEnd = object.loopEnd ?? 0;
    message.clearRegion = object.clearRegion ?? false;
    return message;
  },
};

function createBaseSetMonitor(): SetMonitor {
  return { trackId: "", solo: false, mute: false };
}

export const SetMonitor: MessageFns<SetMonitor> = {
  encode(message: SetMonitor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.solo !== false) {
      writer.uint32(16).bool(message.solo);
    }
    if (message.mute !== false) {
      writer.uint32(24).bool(message.mute);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMonitor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSetMonitor();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.solo = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.mute = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SetMonitor {
    return {
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      solo: isSet(object.solo) ? globalThis.Boolean(object.solo) : false,
      mute: isSet(object.mute) ? globalThis.Boolean(object.mute) : false,
    };
  },

  toJSON(message: SetMonitor): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.solo !== false) {
      obj.solo = message.solo;
    }
    if (message.mute !== false) {
      obj.mute = message.mute;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMonitor>, I>>(base?: I): SetMonitor {
    return SetMonitor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMonitor>, I>>(object: I): SetMonitor {
    const message = createBaseSetMonitor();
    message.trackId = object.trackId ?? "";
    message.solo = object.solo ?? false;
    message.mute = object.mute ?? false;
    return message;
  },
};

function createBaseTapControl(): TapControl {
  return { enabled: false };
}

export const TapControl: MessageFns<TapControl> = {
  encode(message: TapControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TapControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTapControl();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.enabled = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TapControl {
    return { enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false };
  },

  toJSON(message: TapControl): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TapControl>, I>>(base?: I): TapControl {
    return TapControl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TapControl>, I>>(object: I): TapControl {
    const message = createBaseTapControl();
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseEditorControl(): EditorControl {
  return { nodeId: "", open: false };
}

export const EditorControl: MessageFns<EditorControl> = {
  encode(message: EditorControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.open !== false) {
      writer.uint32(16).bool(message.open);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditorControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEditorControl();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nodeId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.open = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): EditorControl {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      open: isSet(object.open) ? globalThis.Boolean(object.open) : false,
    };
  },

  toJSON(message: EditorControl): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.open !== false) {
      obj.open = message.open;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EditorControl>, I>>(base?: I): EditorControl {
    return EditorControl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EditorControl>, I>>(object: I): EditorControl {
    const message = createBaseEditorControl();
    message.nodeId = object.nodeId ?? "";
    message.open = object.open ?? false;
    return message;
  },
};

function createBaseSessionLaunch(): SessionLaunch {
  return { sceneId: "", trackId: "", stop: false, quantize: false };
}

export const SessionLaunch: MessageFns<SessionLaunch> = {
  encode(message: SessionLaunch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sceneId !== "") {
      writer.uint32(10).string(message.sceneId);
    }
    if (message.trackId !== "") {
      writer.uint32(18).string(message.trackId);
    }
    if (message.stop !== false) {
      writer.uint32(24).bool(message.stop);
    }
    if (message.quantize !== false) {
      writer.uint32(32).bool(message.quantize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionLaunch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSessionLaunch();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.sceneId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.stop = reader.bool();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.quantize = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SessionLaunch {
    return {
      sceneId: isSet(object.sceneId)
        ? globalThis.String(object.sceneId)
        : isSet(object.scene_id)
        ? globalThis.String(object.scene_id)
        : "",
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      stop: isSet(object.stop) ? globalThis.Boolean(object.stop) : false,
      quantize: isSet(object.quantize) ? globalThis.Boolean(object.quantize) : false,
    };
  },

  toJSON(message: SessionLaunch): unknown {
    const obj: any = {};
    if (message.sceneId !== "") {
      obj.sceneId = message.sceneId;
    }
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.stop !== false) {
      obj.stop = message.stop;
    }
    if (message.quantize !== false) {
      obj.quantize = message.quantize;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionLaunch>, I>>(base?: I): SessionLaunch {
    return SessionLaunch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionLaunch>, I>>(object: I): SessionLaunch {
    const message = createBaseSessionLaunch();
    message.sceneId = object.sceneId ?? "";
    message.trackId = object.trackId ?? "";
    message.stop = object.stop ?? false;
    message.quantize = object.quantize ?? false;
    return message;
  },
};

function createBaseSessionState(): SessionState {
  return { slots: [] };
}

export const SessionState: MessageFns<SessionState> = {
  encode(message: SessionState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.slots) {
      SessionState_Slot.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSessionState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.slots.push(SessionState_Slot.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SessionState {
    return {
      slots: globalThis.Array.isArray(object?.slots) ? object.slots.map((e: any) => SessionState_Slot.fromJSON(e)) : [],
    };
  },

  toJSON(message: SessionState): unknown {
    const obj: any = {};
    if (message.slots?.length) {
      obj.slots = message.slots.map((e) => SessionState_Slot.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionState>, I>>(base?: I): SessionState {
    return SessionState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionState>, I>>(object: I): SessionState {
    const message = createBaseSessionState();
    message.slots = object.slots?.map((e) => SessionState_Slot.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSessionState_Slot(): SessionState_Slot {
  return { trackId: "", sceneId: "", queued: false };
}

export const SessionState_Slot: MessageFns<SessionState_Slot> = {
  encode(message: SessionState_Slot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.sceneId !== "") {
      writer.uint32(18).string(message.sceneId);
    }
    if (message.queued !== false) {
      writer.uint32(24).bool(message.queued);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionState_Slot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSessionState_Slot();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.sceneId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.queued = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SessionState_Slot {
    return {
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      sceneId: isSet(object.sceneId)
        ? globalThis.String(object.sceneId)
        : isSet(object.scene_id)
        ? globalThis.String(object.scene_id)
        : "",
      queued: isSet(object.queued) ? globalThis.Boolean(object.queued) : false,
    };
  },

  toJSON(message: SessionState_Slot): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.sceneId !== "") {
      obj.sceneId = message.sceneId;
    }
    if (message.queued !== false) {
      obj.queued = message.queued;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionState_Slot>, I>>(base?: I): SessionState_Slot {
    return SessionState_Slot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionState_Slot>, I>>(object: I): SessionState_Slot {
    const message = createBaseSessionState_Slot();
    message.trackId = object.trackId ?? "";
    message.sceneId = object.sceneId ?? "";
    message.queued = object.queued ?? false;
    return message;
  },
};

function createBaseTransportPosition(): TransportPosition {
  return { positionSamples: 0, isPlaying: false, sampleRate: 0 };
}

export const TransportPosition: MessageFns<TransportPosition> = {
  encode(message: TransportPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.positionSamples !== 0) {
      writer.uint32(8).int64(message.positionSamples);
    }
    if (message.isPlaying !== false) {
      writer.uint32(16).bool(message.isPlaying);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(24).uint32(message.sampleRate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransportPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransportPosition();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.positionSamples = longToNumber(reader.int64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.isPlaying = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.sampleRate = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransportPosition {
    return {
      positionSamples: isSet(object.positionSamples)
        ? globalThis.Number(object.positionSamples)
        : isSet(object.position_samples)
        ? globalThis.Number(object.position_samples)
        : 0,
      isPlaying: isSet(object.isPlaying)
        ? globalThis.Boolean(object.isPlaying)
        : isSet(object.is_playing)
        ? globalThis.Boolean(object.is_playing)
        : false,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
    };
  },

  toJSON(message: TransportPosition): unknown {
    const obj: any = {};
    if (message.positionSamples !== 0) {
      obj.positionSamples = Math.round(message.positionSamples);
    }
    if (message.isPlaying !== false) {
      obj.isPlaying = message.isPlaying;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransportPosition>, I>>(base?: I): TransportPosition {
    return TransportPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransportPosition>, I>>(object: I): TransportPosition {
    const message = createBaseTransportPosition();
    message.positionSamples = object.positionSamples ?? 0;
    message.isPlaying = object.isPlaying ?? false;
    message.sampleRate = object.sampleRate ?? 0;
    return message;
  },
};

function createBaseTrackMeter(): TrackMeter {
  return { trackId: "", peakLeft: 0, peakRight: 0 };
}

export const TrackMeter: MessageFns<TrackMeter> = {
  encode(message: TrackMeter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.peakLeft !== 0) {
      writer.uint32(21).float(message.peakLeft);
    }
    if (message.peakRight !== 0) {
      writer.uint32(29).float(message.peakRight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TrackMeter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTrackMeter();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.peakLeft = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.peakRight = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TrackMeter {
    return {
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      peakLeft: isSet(object.peakLeft)
        ? globalThis.Number(object.peakLeft)
        : isSet(object.peak_left)
        ? globalThis.Number(object.peak_left)
        : 0,
      peakRight: isSet(object.peakRight)
        ? globalThis.Number(object.peakRight)
        : isSet(object.peak_right)
        ? globalThis.Number(object.peak_right)
        : 0,
    };
  },

  toJSON(message: TrackMeter): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.peakLeft !== 0) {
      obj.peakLeft = message.peakLeft;
    }
    if (message.peakRight !== 0) {
      obj.peakRight = message.peakRight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackMeter>, I>>(base?: I): TrackMeter {
    return TrackMeter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackMeter>, I>>(object: I): TrackMeter {
    const message = createBaseTrackMeter();
    message.trackId = object.trackId ?? "";
    message.peakLeft = object.peakLeft ?? 0;
    message.peakRight = object.peakRight ?? 0;
    return message;
  },
};

function createBaseMeters(): Meters {
  return { tracks: [], masterPeakLeft: 0, masterPeakRight: 0 };
}

export const Meters: MessageFns<Meters> = {
  encode(message: Meters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tracks) {
      TrackMeter.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.masterPeakLeft !== 0) {
      writer.uint32(21).float(message.masterPeakLeft);
    }
    if (message.masterPeakRight !== 0) {
      writer.uint32(29).float(message.masterPeakRight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Meters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMeters();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.tracks.push(TrackMeter.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.masterPeakLeft = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.masterPeakRight = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Meters {
    return {
      tracks: globalThis.Array.isArray(object?.tracks) ? object.tracks.map((e: any) => TrackMeter.fromJSON(e)) : [],
      masterPeakLeft: isSet(object.masterPeakLeft)
        ? globalThis.Number(object.masterPeakLeft)
        : isSet(object.master_peak_left)
        ? globalThis.Number(object.master_peak_left)
        : 0,
      masterPeakRight: isSet(object.masterPeakRight)
        ? globalThis.Number(object.masterPeakRight)
        : isSet(object.master_peak_right)
        ? globalThis.Number(object.master_peak_right)
        : 0,
    };
  },

  toJSON(message: Meters): unknown {
    const obj: any = {};
    if (message.tracks?.length) {
      obj.tracks = message.tracks.map((e) => TrackMeter.toJSON(e));
    }
    if (message.masterPeakLeft !== 0) {
      obj.masterPeakLeft = message.masterPeakLeft;
    }
    if (message.masterPeakRight !== 0) {
      obj.masterPeakRight = message.masterPeakRight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Meters>, I>>(base?: I): Meters {
    return Meters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Meters>, I>>(object: I): Meters {
    const message = createBaseMeters();
    message.tracks = object.tracks?.map((e) => TrackMeter.fromPartial(e)) || [];
    message.masterPeakLeft = object.masterPeakLeft ?? 0;
    message.masterPeakRight = object.masterPeakRight ?? 0;
    return message;
  },
};

function createBaseEngineState(): EngineState {
  return {
    bufferUnderruns: 0,
    cpuPercent: 0,
    latencySamples: 0,
    pluginBlocksMissed: 0,
    pluginChildAlive: false,
    pluginChildRestarts: 0,
    projectId: "",
    stemsRenderedTotal: 0,
    devicePeriodFrames: 0,
    deviceExclusive: false,
    limiterReductionDb: 0,
    limiterEngagedBlocks: 0,
    limiterCeilingDb: 0,
    limiterEnabled: false,
  };
}

export const EngineState: MessageFns<EngineState> = {
  encode(message: EngineState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bufferUnderruns !== 0) {
      writer.uint32(8).uint64(message.bufferUnderruns);
    }
    if (message.cpuPercent !== 0) {
      writer.uint32(16).uint32(message.cpuPercent);
    }
    if (message.latencySamples !== 0) {
      writer.uint32(24).uint32(message.latencySamples);
    }
    if (message.pluginBlocksMissed !== 0) {
      writer.uint32(32).uint64(message.pluginBlocksMissed);
    }
    if (message.pluginChildAlive !== false) {
      writer.uint32(40).bool(message.pluginChildAlive);
    }
    if (message.pluginChildRestarts !== 0) {
      writer.uint32(48).uint32(message.pluginChildRestarts);
    }
    if (message.projectId !== "") {
      writer.uint32(58).string(message.projectId);
    }
    if (message.stemsRenderedTotal !== 0) {
      writer.uint32(64).uint32(message.stemsRenderedTotal);
    }
    if (message.devicePeriodFrames !== 0) {
      writer.uint32(72).uint32(message.devicePeriodFrames);
    }
    if (message.deviceExclusive !== false) {
      writer.uint32(80).bool(message.deviceExclusive);
    }
    if (message.limiterReductionDb !== 0) {
      writer.uint32(93).float(message.limiterReductionDb);
    }
    if (message.limiterEngagedBlocks !== 0) {
      writer.uint32(96).uint64(message.limiterEngagedBlocks);
    }
    if (message.limiterCeilingDb !== 0) {
      writer.uint32(109).float(message.limiterCeilingDb);
    }
    if (message.limiterEnabled !== false) {
      writer.uint32(112).bool(message.limiterEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EngineState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEngineState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.bufferUnderruns = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.cpuPercent = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.latencySamples = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.pluginBlocksMissed = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.pluginChildAlive = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.pluginChildRestarts = reader.uint32();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.projectId = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.stemsRenderedTotal = reader.uint32();
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.devicePeriodFrames = reader.uint32();
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.deviceExclusive = reader.bool();
            continue;
          }
          case 11: {
            if (tag !== 93) {
              break;
            }

            message.limiterReductionDb = reader.float();
            continue;
          }
          case 12: {
            if (tag !== 96) {
              break;
            }

            message.limiterEngagedBlocks = longToNumber(reader.uint64());
            continue;
          }
          case 13: {
            if (tag !== 109) {
              break;
            }

            message.limiterCeilingDb = reader.float();
            continue;
          }
          case 14: {
            if (tag !== 112) {
              break;
            }

            message.limiterEnabled = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): EngineState {
    return {
      bufferUnderruns: isSet(object.bufferUnderruns)
        ? globalThis.Number(object.bufferUnderruns)
        : isSet(object.buffer_underruns)
        ? globalThis.Number(object.buffer_underruns)
        : 0,
      cpuPercent: isSet(object.cpuPercent)
        ? globalThis.Number(object.cpuPercent)
        : isSet(object.cpu_percent)
        ? globalThis.Number(object.cpu_percent)
        : 0,
      latencySamples: isSet(object.latencySamples)
        ? globalThis.Number(object.latencySamples)
        : isSet(object.latency_samples)
        ? globalThis.Number(object.latency_samples)
        : 0,
      pluginBlocksMissed: isSet(object.pluginBlocksMissed)
        ? globalThis.Number(object.pluginBlocksMissed)
        : isSet(object.plugin_blocks_missed)
        ? globalThis.Number(object.plugin_blocks_missed)
        : 0,
      pluginChildAlive: isSet(object.pluginChildAlive)
        ? globalThis.Boolean(object.pluginChildAlive)
        : isSet(object.plugin_child_alive)
        ? globalThis.Boolean(object.plugin_child_alive)
        : false,
      pluginChildRestarts: isSet(object.pluginChildRestarts)
        ? globalThis.Number(object.pluginChildRestarts)
        : isSet(object.plugin_child_restarts)
        ? globalThis.Number(object.plugin_child_restarts)
        : 0,
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
      stemsRenderedTotal: isSet(object.stemsRenderedTotal)
        ? globalThis.Number(object.stemsRenderedTotal)
        : isSet(object.stems_rendered_total)
        ? globalThis.Number(object.stems_rendered_total)
        : 0,
      devicePeriodFrames: isSet(object.devicePeriodFrames)
        ? globalThis.Number(object.devicePeriodFrames)
        : isSet(object.device_period_frames)
        ? globalThis.Number(object.device_period_frames)
        : 0,
      deviceExclusive: isSet(object.deviceExclusive)
        ? globalThis.Boolean(object.deviceExclusive)
        : isSet(object.device_exclusive)
        ? globalThis.Boolean(object.device_exclusive)
        : false,
      limiterReductionDb: isSet(object.limiterReductionDb)
        ? globalThis.Number(object.limiterReductionDb)
        : isSet(object.limiter_reduction_db)
        ? globalThis.Number(object.limiter_reduction_db)
        : 0,
      limiterEngagedBlocks: isSet(object.limiterEngagedBlocks)
        ? globalThis.Number(object.limiterEngagedBlocks)
        : isSet(object.limiter_engaged_blocks)
        ? globalThis.Number(object.limiter_engaged_blocks)
        : 0,
      limiterCeilingDb: isSet(object.limiterCeilingDb)
        ? globalThis.Number(object.limiterCeilingDb)
        : isSet(object.limiter_ceiling_db)
        ? globalThis.Number(object.limiter_ceiling_db)
        : 0,
      limiterEnabled: isSet(object.limiterEnabled)
        ? globalThis.Boolean(object.limiterEnabled)
        : isSet(object.limiter_enabled)
        ? globalThis.Boolean(object.limiter_enabled)
        : false,
    };
  },

  toJSON(message: EngineState): unknown {
    const obj: any = {};
    if (message.bufferUnderruns !== 0) {
      obj.bufferUnderruns = Math.round(message.bufferUnderruns);
    }
    if (message.cpuPercent !== 0) {
      obj.cpuPercent = Math.round(message.cpuPercent);
    }
    if (message.latencySamples !== 0) {
      obj.latencySamples = Math.round(message.latencySamples);
    }
    if (message.pluginBlocksMissed !== 0) {
      obj.pluginBlocksMissed = Math.round(message.pluginBlocksMissed);
    }
    if (message.pluginChildAlive !== false) {
      obj.pluginChildAlive = message.pluginChildAlive;
    }
    if (message.pluginChildRestarts !== 0) {
      obj.pluginChildRestarts = Math.round(message.pluginChildRestarts);
    }
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    if (message.stemsRenderedTotal !== 0) {
      obj.stemsRenderedTotal = Math.round(message.stemsRenderedTotal);
    }
    if (message.devicePeriodFrames !== 0) {
      obj.devicePeriodFrames = Math.round(message.devicePeriodFrames);
    }
    if (message.deviceExclusive !== false) {
      obj.deviceExclusive = message.deviceExclusive;
    }
    if (message.limiterReductionDb !== 0) {
      obj.limiterReductionDb = message.limiterReductionDb;
    }
    if (message.limiterEngagedBlocks !== 0) {
      obj.limiterEngagedBlocks = Math.round(message.limiterEngagedBlocks);
    }
    if (message.limiterCeilingDb !== 0) {
      obj.limiterCeilingDb = message.limiterCeilingDb;
    }
    if (message.limiterEnabled !== false) {
      obj.limiterEnabled = message.limiterEnabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EngineState>, I>>(base?: I): EngineState {
    return EngineState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EngineState>, I>>(object: I): EngineState {
    const message = createBaseEngineState();
    message.bufferUnderruns = object.bufferUnderruns ?? 0;
    message.cpuPercent = object.cpuPercent ?? 0;
    message.latencySamples = object.latencySamples ?? 0;
    message.pluginBlocksMissed = object.pluginBlocksMissed ?? 0;
    message.pluginChildAlive = object.pluginChildAlive ?? false;
    message.pluginChildRestarts = object.pluginChildRestarts ?? 0;
    message.projectId = object.projectId ?? "";
    message.stemsRenderedTotal = object.stemsRenderedTotal ?? 0;
    message.devicePeriodFrames = object.devicePeriodFrames ?? 0;
    message.deviceExclusive = object.deviceExclusive ?? false;
    message.limiterReductionDb = object.limiterReductionDb ?? 0;
    message.limiterEngagedBlocks = object.limiterEngagedBlocks ?? 0;
    message.limiterCeilingDb = object.limiterCeilingDb ?? 0;
    message.limiterEnabled = object.limiterEnabled ?? false;
    return message;
  },
};

function createBaseAudioTap(): AudioTap {
  return { firstSeq: 0, blockCount: 0, samples: new Uint8Array(0), droppedBlocks: 0 };
}

export const AudioTap: MessageFns<AudioTap> = {
  encode(message: AudioTap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstSeq !== 0) {
      writer.uint32(8).uint64(message.firstSeq);
    }
    if (message.blockCount !== 0) {
      writer.uint32(16).uint32(message.blockCount);
    }
    if (message.samples.length !== 0) {
      writer.uint32(26).bytes(message.samples);
    }
    if (message.droppedBlocks !== 0) {
      writer.uint32(32).uint64(message.droppedBlocks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioTap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAudioTap();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.firstSeq = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.blockCount = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.samples = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.droppedBlocks = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): AudioTap {
    return {
      firstSeq: isSet(object.firstSeq)
        ? globalThis.Number(object.firstSeq)
        : isSet(object.first_seq)
        ? globalThis.Number(object.first_seq)
        : 0,
      blockCount: isSet(object.blockCount)
        ? globalThis.Number(object.blockCount)
        : isSet(object.block_count)
        ? globalThis.Number(object.block_count)
        : 0,
      samples: isSet(object.samples) ? bytesFromBase64(object.samples) : new Uint8Array(0),
      droppedBlocks: isSet(object.droppedBlocks)
        ? globalThis.Number(object.droppedBlocks)
        : isSet(object.dropped_blocks)
        ? globalThis.Number(object.dropped_blocks)
        : 0,
    };
  },

  toJSON(message: AudioTap): unknown {
    const obj: any = {};
    if (message.firstSeq !== 0) {
      obj.firstSeq = Math.round(message.firstSeq);
    }
    if (message.blockCount !== 0) {
      obj.blockCount = Math.round(message.blockCount);
    }
    if (message.samples.length !== 0) {
      obj.samples = base64FromBytes(message.samples);
    }
    if (message.droppedBlocks !== 0) {
      obj.droppedBlocks = Math.round(message.droppedBlocks);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioTap>, I>>(base?: I): AudioTap {
    return AudioTap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioTap>, I>>(object: I): AudioTap {
    const message = createBaseAudioTap();
    message.firstSeq = object.firstSeq ?? 0;
    message.blockCount = object.blockCount ?? 0;
    message.samples = object.samples ?? new Uint8Array(0);
    message.droppedBlocks = object.droppedBlocks ?? 0;
    return message;
  },
};

function createBaseRenderRequest(): RenderRequest {
  return { bitDepth: 0 };
}

export const RenderRequest: MessageFns<RenderRequest> = {
  encode(message: RenderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bitDepth !== 0) {
      writer.uint32(8).uint32(message.bitDepth);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RenderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRenderRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.bitDepth = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RenderRequest {
    return {
      bitDepth: isSet(object.bitDepth)
        ? globalThis.Number(object.bitDepth)
        : isSet(object.bit_depth)
        ? globalThis.Number(object.bit_depth)
        : 0,
    };
  },

  toJSON(message: RenderRequest): unknown {
    const obj: any = {};
    if (message.bitDepth !== 0) {
      obj.bitDepth = Math.round(message.bitDepth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RenderRequest>, I>>(base?: I): RenderRequest {
    return RenderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RenderRequest>, I>>(object: I): RenderRequest {
    const message = createBaseRenderRequest();
    message.bitDepth = object.bitDepth ?? 0;
    return message;
  },
};

function createBaseRenderState(): RenderState {
  return { status: 0, wavHash: "", error: "", lengthSamples: 0, sampleRate: 0, bitDepth: 0 };
}

export const RenderState: MessageFns<RenderState> = {
  encode(message: RenderState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.wavHash !== "") {
      writer.uint32(18).string(message.wavHash);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    if (message.lengthSamples !== 0) {
      writer.uint32(32).uint64(message.lengthSamples);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(40).uint32(message.sampleRate);
    }
    if (message.bitDepth !== 0) {
      writer.uint32(48).uint32(message.bitDepth);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RenderState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRenderState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.status = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.wavHash = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.error = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.lengthSamples = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.sampleRate = reader.uint32();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.bitDepth = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RenderState {
    return {
      status: isSet(object.status) ? renderState_StatusFromJSON(object.status) : 0,
      wavHash: isSet(object.wavHash)
        ? globalThis.String(object.wavHash)
        : isSet(object.wav_hash)
        ? globalThis.String(object.wav_hash)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      lengthSamples: isSet(object.lengthSamples)
        ? globalThis.Number(object.lengthSamples)
        : isSet(object.length_samples)
        ? globalThis.Number(object.length_samples)
        : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      bitDepth: isSet(object.bitDepth)
        ? globalThis.Number(object.bitDepth)
        : isSet(object.bit_depth)
        ? globalThis.Number(object.bit_depth)
        : 0,
    };
  },

  toJSON(message: RenderState): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = renderState_StatusToJSON(message.status);
    }
    if (message.wavHash !== "") {
      obj.wavHash = message.wavHash;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.lengthSamples !== 0) {
      obj.lengthSamples = Math.round(message.lengthSamples);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.bitDepth !== 0) {
      obj.bitDepth = Math.round(message.bitDepth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RenderState>, I>>(base?: I): RenderState {
    return RenderState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RenderState>, I>>(object: I): RenderState {
    const message = createBaseRenderState();
    message.status = object.status ?? 0;
    message.wavHash = object.wavHash ?? "";
    message.error = object.error ?? "";
    message.lengthSamples = object.lengthSamples ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.bitDepth = object.bitDepth ?? 0;
    return message;
  },
};

function createBaseSwitchProject(): SwitchProject {
  return { projectId: "" };
}

export const SwitchProject: MessageFns<SwitchProject> = {
  encode(message: SwitchProject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SwitchProject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSwitchProject();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.projectId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SwitchProject {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
    };
  },

  toJSON(message: SwitchProject): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwitchProject>, I>>(base?: I): SwitchProject {
    return SwitchProject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwitchProject>, I>>(object: I): SwitchProject {
    const message = createBaseSwitchProject();
    message.projectId = object.projectId ?? "";
    return message;
  },
};

function createBasePluginEntry(): PluginEntry {
  return { uid: "", name: "", vendor: "", subCategories: "" };
}

export const PluginEntry: MessageFns<PluginEntry> = {
  encode(message: PluginEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.vendor !== "") {
      writer.uint32(26).string(message.vendor);
    }
    if (message.subCategories !== "") {
      writer.uint32(34).string(message.subCategories);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePluginEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.uid = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.vendor = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.subCategories = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PluginEntry {
    return {
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      vendor: isSet(object.vendor) ? globalThis.String(object.vendor) : "",
      subCategories: isSet(object.subCategories)
        ? globalThis.String(object.subCategories)
        : isSet(object.sub_categories)
        ? globalThis.String(object.sub_categories)
        : "",
    };
  },

  toJSON(message: PluginEntry): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.vendor !== "") {
      obj.vendor = message.vendor;
    }
    if (message.subCategories !== "") {
      obj.subCategories = message.subCategories;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginEntry>, I>>(base?: I): PluginEntry {
    return PluginEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginEntry>, I>>(object: I): PluginEntry {
    const message = createBasePluginEntry();
    message.uid = object.uid ?? "";
    message.name = object.name ?? "";
    message.vendor = object.vendor ?? "";
    message.subCategories = object.subCategories ?? "";
    return message;
  },
};

function createBasePluginCatalog(): PluginCatalog {
  return { entries: [] };
}

export const PluginCatalog: MessageFns<PluginCatalog> = {
  encode(message: PluginCatalog, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      PluginEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginCatalog {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePluginCatalog();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.entries.push(PluginEntry.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PluginCatalog {
    return {
      entries: globalThis.Array.isArray(object?.entries) ? object.entries.map((e: any) => PluginEntry.fromJSON(e)) : [],
    };
  },

  toJSON(message: PluginCatalog): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => PluginEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginCatalog>, I>>(base?: I): PluginCatalog {
    return PluginCatalog.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginCatalog>, I>>(object: I): PluginCatalog {
    const message = createBasePluginCatalog();
    message.entries = object.entries?.map((e) => PluginEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseError(): Error {
  return { severity: 0, code: "", message: "" };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.severity !== 0) {
      writer.uint32(8).int32(message.severity);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseError();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.severity = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.message = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Error {
    return {
      severity: isSet(object.severity) ? error_SeverityFromJSON(object.severity) : 0,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.severity !== 0) {
      obj.severity = error_SeverityToJSON(message.severity);
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.severity = object.severity ?? 0;
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    transport: undefined,
    setMonitor: undefined,
    tapControl: undefined,
    editor: undefined,
    sessionLaunch: undefined,
    renderRequest: undefined,
    switchProject: undefined,
    position: undefined,
    meters: undefined,
    engineState: undefined,
    error: undefined,
    audioTap: undefined,
    pluginCatalog: undefined,
    sessionState: undefined,
    renderState: undefined,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transport !== undefined) {
      TransportCommand.encode(message.transport, writer.uint32(10).fork()).join();
    }
    if (message.setMonitor !== undefined) {
      SetMonitor.encode(message.setMonitor, writer.uint32(18).fork()).join();
    }
    if (message.tapControl !== undefined) {
      TapControl.encode(message.tapControl, writer.uint32(58).fork()).join();
    }
    if (message.editor !== undefined) {
      EditorControl.encode(message.editor, writer.uint32(82).fork()).join();
    }
    if (message.sessionLaunch !== undefined) {
      SessionLaunch.encode(message.sessionLaunch, writer.uint32(90).fork()).join();
    }
    if (message.renderRequest !== undefined) {
      RenderRequest.encode(message.renderRequest, writer.uint32(106).fork()).join();
    }
    if (message.switchProject !== undefined) {
      SwitchProject.encode(message.switchProject, writer.uint32(122).fork()).join();
    }
    if (message.position !== undefined) {
      TransportPosition.encode(message.position, writer.uint32(26).fork()).join();
    }
    if (message.meters !== undefined) {
      Meters.encode(message.meters, writer.uint32(34).fork()).join();
    }
    if (message.engineState !== undefined) {
      EngineState.encode(message.engineState, writer.uint32(42).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(50).fork()).join();
    }
    if (message.audioTap !== undefined) {
      AudioTap.encode(message.audioTap, writer.uint32(66).fork()).join();
    }
    if (message.pluginCatalog !== undefined) {
      PluginCatalog.encode(message.pluginCatalog, writer.uint32(74).fork()).join();
    }
    if (message.sessionState !== undefined) {
      SessionState.encode(message.sessionState, writer.uint32(98).fork()).join();
    }
    if (message.renderState !== undefined) {
      RenderState.encode(message.renderState, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transport = TransportCommand.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.setMonitor = SetMonitor.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.tapControl = TapControl.decode(reader, reader.uint32());
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.editor = EditorControl.decode(reader, reader.uint32());
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.sessionLaunch = SessionLaunch.decode(reader, reader.uint32());
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.renderRequest = RenderRequest.decode(reader, reader.uint32());
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.switchProject = SwitchProject.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.position = TransportPosition.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.meters = Meters.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.engineState = EngineState.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.error = Error.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.audioTap = AudioTap.decode(reader, reader.uint32());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.pluginCatalog = PluginCatalog.decode(reader, reader.uint32());
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.sessionState = SessionState.decode(reader, reader.uint32());
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            message.renderState = RenderState.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Message {
    return {
      transport: isSet(object.transport) ? TransportCommand.fromJSON(object.transport) : undefined,
      setMonitor: isSet(object.setMonitor)
        ? SetMonitor.fromJSON(object.setMonitor)
        : isSet(object.set_monitor)
        ? SetMonitor.fromJSON(object.set_monitor)
        : undefined,
      tapControl: isSet(object.tapControl)
        ? TapControl.fromJSON(object.tapControl)
        : isSet(object.tap_control)
        ? TapControl.fromJSON(object.tap_control)
        : undefined,
      editor: isSet(object.editor) ? EditorControl.fromJSON(object.editor) : undefined,
      sessionLaunch: isSet(object.sessionLaunch)
        ? SessionLaunch.fromJSON(object.sessionLaunch)
        : isSet(object.session_launch)
        ? SessionLaunch.fromJSON(object.session_launch)
        : undefined,
      renderRequest: isSet(object.renderRequest)
        ? RenderRequest.fromJSON(object.renderRequest)
        : isSet(object.render_request)
        ? RenderRequest.fromJSON(object.render_request)
        : undefined,
      switchProject: isSet(object.switchProject)
        ? SwitchProject.fromJSON(object.switchProject)
        : isSet(object.switch_project)
        ? SwitchProject.fromJSON(object.switch_project)
        : undefined,
      position: isSet(object.position) ? TransportPosition.fromJSON(object.position) : undefined,
      meters: isSet(object.meters) ? Meters.fromJSON(object.meters) : undefined,
      engineState: isSet(object.engineState)
        ? EngineState.fromJSON(object.engineState)
        : isSet(object.engine_state)
        ? EngineState.fromJSON(object.engine_state)
        : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      audioTap: isSet(object.audioTap)
        ? AudioTap.fromJSON(object.audioTap)
        : isSet(object.audio_tap)
        ? AudioTap.fromJSON(object.audio_tap)
        : undefined,
      pluginCatalog: isSet(object.pluginCatalog)
        ? PluginCatalog.fromJSON(object.pluginCatalog)
        : isSet(object.plugin_catalog)
        ? PluginCatalog.fromJSON(object.plugin_catalog)
        : undefined,
      sessionState: isSet(object.sessionState)
        ? SessionState.fromJSON(object.sessionState)
        : isSet(object.session_state)
        ? SessionState.fromJSON(object.session_state)
        : undefined,
      renderState: isSet(object.renderState)
        ? RenderState.fromJSON(object.renderState)
        : isSet(object.render_state)
        ? RenderState.fromJSON(object.render_state)
        : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.transport !== undefined) {
      obj.transport = TransportCommand.toJSON(message.transport);
    }
    if (message.setMonitor !== undefined) {
      obj.setMonitor = SetMonitor.toJSON(message.setMonitor);
    }
    if (message.tapControl !== undefined) {
      obj.tapControl = TapControl.toJSON(message.tapControl);
    }
    if (message.editor !== undefined) {
      obj.editor = EditorControl.toJSON(message.editor);
    }
    if (message.sessionLaunch !== undefined) {
      obj.sessionLaunch = SessionLaunch.toJSON(message.sessionLaunch);
    }
    if (message.renderRequest !== undefined) {
      obj.renderRequest = RenderRequest.toJSON(message.renderRequest);
    }
    if (message.switchProject !== undefined) {
      obj.switchProject = SwitchProject.toJSON(message.switchProject);
    }
    if (message.position !== undefined) {
      obj.position = TransportPosition.toJSON(message.position);
    }
    if (message.meters !== undefined) {
      obj.meters = Meters.toJSON(message.meters);
    }
    if (message.engineState !== undefined) {
      obj.engineState = EngineState.toJSON(message.engineState);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.audioTap !== undefined) {
      obj.audioTap = AudioTap.toJSON(message.audioTap);
    }
    if (message.pluginCatalog !== undefined) {
      obj.pluginCatalog = PluginCatalog.toJSON(message.pluginCatalog);
    }
    if (message.sessionState !== undefined) {
      obj.sessionState = SessionState.toJSON(message.sessionState);
    }
    if (message.renderState !== undefined) {
      obj.renderState = RenderState.toJSON(message.renderState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.transport = (object.transport !== undefined && object.transport !== null)
      ? TransportCommand.fromPartial(object.transport)
      : undefined;
    message.setMonitor = (object.setMonitor !== undefined && object.setMonitor !== null)
      ? SetMonitor.fromPartial(object.setMonitor)
      : undefined;
    message.tapControl = (object.tapControl !== undefined && object.tapControl !== null)
      ? TapControl.fromPartial(object.tapControl)
      : undefined;
    message.editor = (object.editor !== undefined && object.editor !== null)
      ? EditorControl.fromPartial(object.editor)
      : undefined;
    message.sessionLaunch = (object.sessionLaunch !== undefined && object.sessionLaunch !== null)
      ? SessionLaunch.fromPartial(object.sessionLaunch)
      : undefined;
    message.renderRequest = (object.renderRequest !== undefined && object.renderRequest !== null)
      ? RenderRequest.fromPartial(object.renderRequest)
      : undefined;
    message.switchProject = (object.switchProject !== undefined && object.switchProject !== null)
      ? SwitchProject.fromPartial(object.switchProject)
      : undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? TransportPosition.fromPartial(object.position)
      : undefined;
    message.meters = (object.meters !== undefined && object.meters !== null)
      ? Meters.fromPartial(object.meters)
      : undefined;
    message.engineState = (object.engineState !== undefined && object.engineState !== null)
      ? EngineState.fromPartial(object.engineState)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.audioTap = (object.audioTap !== undefined && object.audioTap !== null)
      ? AudioTap.fromPartial(object.audioTap)
      : undefined;
    message.pluginCatalog = (object.pluginCatalog !== undefined && object.pluginCatalog !== null)
      ? PluginCatalog.fromPartial(object.pluginCatalog)
      : undefined;
    message.sessionState = (object.sessionState !== undefined && object.sessionState !== null)
      ? SessionState.fromPartial(object.sessionState)
      : undefined;
    message.renderState = (object.renderState !== undefined && object.renderState !== null)
      ? RenderState.fromPartial(object.renderState)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
