// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.0
// source: src/proto/messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "daw.protocol";

/** SPDX-License-Identifier: GPL-3.0-or-later */

/** Transport control */
export interface TransportCommand {
  action: TransportCommand_Action;
  /** Only used when action == SEEK (in samples) */
  seekPosition: number;
  /** Only used when action == LOOP */
  loopEnabled: boolean;
}

export enum TransportCommand_Action {
  PLAY = 0,
  STOP = 1,
  SEEK = 2,
  /** LOOP - V1.1: toggle looping (performance state, never CRDT) */
  LOOP = 3,
  UNRECOGNIZED = -1,
}

export function transportCommand_ActionFromJSON(object: any): TransportCommand_Action {
  switch (object) {
    case 0:
    case "PLAY":
      return TransportCommand_Action.PLAY;
    case 1:
    case "STOP":
      return TransportCommand_Action.STOP;
    case 2:
    case "SEEK":
      return TransportCommand_Action.SEEK;
    case 3:
    case "LOOP":
      return TransportCommand_Action.LOOP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransportCommand_Action.UNRECOGNIZED;
  }
}

export function transportCommand_ActionToJSON(object: TransportCommand_Action): string {
  switch (object) {
    case TransportCommand_Action.PLAY:
      return "PLAY";
    case TransportCommand_Action.STOP:
      return "STOP";
    case TransportCommand_Action.SEEK:
      return "SEEK";
    case TransportCommand_Action.LOOP:
      return "LOOP";
    case TransportCommand_Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Monitor control (solo/mute per track - local to this client) */
export interface SetMonitor {
  trackId: string;
  solo: boolean;
  mute: boolean;
}

/**
 * S8a: subscribe/unsubscribe this client to the master tap (the jam
 * road: engine -> LOCAL tab over loopback; the tab ships it P2P)
 */
export interface TapControl {
  enabled: boolean;
}

/** Transport position (sent at 30 Hz) */
export interface TransportPosition {
  positionSamples: number;
  isPlaying: boolean;
  /**
   * AUDIT-5 A8: the engine's real device sample rate, so the web stops
   * hardcoding 48000 (the playhead drifts 8.8% on a 44.1k device).
   * Additive: 0 (absent, old engine) -> the web keeps its 48000 fallback.
   */
  sampleRate: number;
}

/** Per-track meter levels */
export interface TrackMeter {
  trackId: string;
  peakLeft: number;
  peakRight: number;
}

/** All meters (sent at 30 Hz) */
export interface Meters {
  tracks: TrackMeter[];
  /** V1.2: post-master-gain output peaks - */
  masterPeakLeft: number;
  /** the browser had NO master path before */
  masterPeakRight: number;
}

/** Engine state (sent at 30 Hz with telemetry) */
export interface EngineState {
  /** Cumulative underrun count */
  bufferUnderruns: number;
  /** Audio thread CPU usage (0-100) */
  cpuPercent: number;
  /** Current output latency */
  latencySamples: number;
  /** 2.4c-1: bridge blocks bypassed (child late/dead) */
  pluginBlocksMissed: number;
  /** c-2: false during a death window / permanent bypass */
  pluginChildAlive: boolean;
  /** c-2: cold restart attempts (budget 3) */
  pluginChildRestarts: number;
}

/**
 * S8a: a batch of post-master audio blocks for the subscribed tab.
 * first_seq counts 256-frame blocks since tap start; a seq gap = the
 * control thread fell behind and the ring dropped (counted, visible).
 * Samples are interleaved stereo float32, little-endian.
 */
export interface AudioTap {
  firstSeq: number;
  blockCount: number;
  /** block_count * 256 * 2 * 4 bytes */
  samples: Uint8Array;
  /** cumulative ring overruns */
  droppedBlocks: number;
}

/** 2.5-decouverte: one scanned plugin class (Audio Module Class only) */
export interface PluginEntry {
  /** 32-hex VST3 class id */
  uid: string;
  name: string;
  vendor: string;
  /** e.g. "Fx|Dynamics|Stereo", "Instrument|Synth" */
  subCategories: string;
}

/**
 * The engine's plugin catalog: scanned from --vst3-dir folders (cache
 * by path+size+mtime, enumeration in the crash-isolated child), plus
 * explicit --vst3-module mappings. Sent ONCE per connection, on auth.
 */
export interface PluginCatalog {
  entries: PluginEntry[];
}

/** Error from engine */
export interface Error {
  severity: Error_Severity;
  /** Machine-readable error code */
  code: string;
  /** Human-readable message */
  message: string;
}

export enum Error_Severity {
  WARNING = 0,
  ERROR = 1,
  FATAL = 2,
  UNRECOGNIZED = -1,
}

export function error_SeverityFromJSON(object: any): Error_Severity {
  switch (object) {
    case 0:
    case "WARNING":
      return Error_Severity.WARNING;
    case 1:
    case "ERROR":
      return Error_Severity.ERROR;
    case 2:
    case "FATAL":
      return Error_Severity.FATAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Error_Severity.UNRECOGNIZED;
  }
}

export function error_SeverityToJSON(object: Error_Severity): string {
  switch (object) {
    case Error_Severity.WARNING:
      return "WARNING";
    case Error_Severity.ERROR:
      return "ERROR";
    case Error_Severity.FATAL:
      return "FATAL";
    case Error_Severity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Message {
  /** Client -> Engine */
  transport?: TransportCommand | undefined;
  setMonitor?:
    | SetMonitor
    | undefined;
  /** S8a */
  tapControl?:
    | TapControl
    | undefined;
  /** Engine -> Client */
  position?: TransportPosition | undefined;
  meters?: Meters | undefined;
  engineState?: EngineState | undefined;
  error?:
    | Error
    | undefined;
  /** S8a */
  audioTap?:
    | AudioTap
    | undefined;
  /** 2.5-decouverte */
  pluginCatalog?: PluginCatalog | undefined;
}

function createBaseTransportCommand(): TransportCommand {
  return { action: 0, seekPosition: 0, loopEnabled: false };
}

export const TransportCommand: MessageFns<TransportCommand> = {
  encode(message: TransportCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== 0) {
      writer.uint32(8).int32(message.action);
    }
    if (message.seekPosition !== 0) {
      writer.uint32(16).int64(message.seekPosition);
    }
    if (message.loopEnabled !== false) {
      writer.uint32(24).bool(message.loopEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransportCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransportCommand();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.action = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.seekPosition = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.loopEnabled = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransportCommand {
    return {
      action: isSet(object.action) ? transportCommand_ActionFromJSON(object.action) : 0,
      seekPosition: isSet(object.seekPosition)
        ? globalThis.Number(object.seekPosition)
        : isSet(object.seek_position)
        ? globalThis.Number(object.seek_position)
        : 0,
      loopEnabled: isSet(object.loopEnabled)
        ? globalThis.Boolean(object.loopEnabled)
        : isSet(object.loop_enabled)
        ? globalThis.Boolean(object.loop_enabled)
        : false,
    };
  },

  toJSON(message: TransportCommand): unknown {
    const obj: any = {};
    if (message.action !== 0) {
      obj.action = transportCommand_ActionToJSON(message.action);
    }
    if (message.seekPosition !== 0) {
      obj.seekPosition = Math.round(message.seekPosition);
    }
    if (message.loopEnabled !== false) {
      obj.loopEnabled = message.loopEnabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransportCommand>, I>>(base?: I): TransportCommand {
    return TransportCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransportCommand>, I>>(object: I): TransportCommand {
    const message = createBaseTransportCommand();
    message.action = object.action ?? 0;
    message.seekPosition = object.seekPosition ?? 0;
    message.loopEnabled = object.loopEnabled ?? false;
    return message;
  },
};

function createBaseSetMonitor(): SetMonitor {
  return { trackId: "", solo: false, mute: false };
}

export const SetMonitor: MessageFns<SetMonitor> = {
  encode(message: SetMonitor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.solo !== false) {
      writer.uint32(16).bool(message.solo);
    }
    if (message.mute !== false) {
      writer.uint32(24).bool(message.mute);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMonitor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSetMonitor();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.solo = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.mute = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SetMonitor {
    return {
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      solo: isSet(object.solo) ? globalThis.Boolean(object.solo) : false,
      mute: isSet(object.mute) ? globalThis.Boolean(object.mute) : false,
    };
  },

  toJSON(message: SetMonitor): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.solo !== false) {
      obj.solo = message.solo;
    }
    if (message.mute !== false) {
      obj.mute = message.mute;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMonitor>, I>>(base?: I): SetMonitor {
    return SetMonitor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMonitor>, I>>(object: I): SetMonitor {
    const message = createBaseSetMonitor();
    message.trackId = object.trackId ?? "";
    message.solo = object.solo ?? false;
    message.mute = object.mute ?? false;
    return message;
  },
};

function createBaseTapControl(): TapControl {
  return { enabled: false };
}

export const TapControl: MessageFns<TapControl> = {
  encode(message: TapControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TapControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTapControl();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.enabled = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TapControl {
    return { enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false };
  },

  toJSON(message: TapControl): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TapControl>, I>>(base?: I): TapControl {
    return TapControl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TapControl>, I>>(object: I): TapControl {
    const message = createBaseTapControl();
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseTransportPosition(): TransportPosition {
  return { positionSamples: 0, isPlaying: false, sampleRate: 0 };
}

export const TransportPosition: MessageFns<TransportPosition> = {
  encode(message: TransportPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.positionSamples !== 0) {
      writer.uint32(8).int64(message.positionSamples);
    }
    if (message.isPlaying !== false) {
      writer.uint32(16).bool(message.isPlaying);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(24).uint32(message.sampleRate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransportPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransportPosition();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.positionSamples = longToNumber(reader.int64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.isPlaying = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.sampleRate = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransportPosition {
    return {
      positionSamples: isSet(object.positionSamples)
        ? globalThis.Number(object.positionSamples)
        : isSet(object.position_samples)
        ? globalThis.Number(object.position_samples)
        : 0,
      isPlaying: isSet(object.isPlaying)
        ? globalThis.Boolean(object.isPlaying)
        : isSet(object.is_playing)
        ? globalThis.Boolean(object.is_playing)
        : false,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
    };
  },

  toJSON(message: TransportPosition): unknown {
    const obj: any = {};
    if (message.positionSamples !== 0) {
      obj.positionSamples = Math.round(message.positionSamples);
    }
    if (message.isPlaying !== false) {
      obj.isPlaying = message.isPlaying;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransportPosition>, I>>(base?: I): TransportPosition {
    return TransportPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransportPosition>, I>>(object: I): TransportPosition {
    const message = createBaseTransportPosition();
    message.positionSamples = object.positionSamples ?? 0;
    message.isPlaying = object.isPlaying ?? false;
    message.sampleRate = object.sampleRate ?? 0;
    return message;
  },
};

function createBaseTrackMeter(): TrackMeter {
  return { trackId: "", peakLeft: 0, peakRight: 0 };
}

export const TrackMeter: MessageFns<TrackMeter> = {
  encode(message: TrackMeter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.peakLeft !== 0) {
      writer.uint32(21).float(message.peakLeft);
    }
    if (message.peakRight !== 0) {
      writer.uint32(29).float(message.peakRight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TrackMeter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTrackMeter();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.trackId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.peakLeft = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.peakRight = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TrackMeter {
    return {
      trackId: isSet(object.trackId)
        ? globalThis.String(object.trackId)
        : isSet(object.track_id)
        ? globalThis.String(object.track_id)
        : "",
      peakLeft: isSet(object.peakLeft)
        ? globalThis.Number(object.peakLeft)
        : isSet(object.peak_left)
        ? globalThis.Number(object.peak_left)
        : 0,
      peakRight: isSet(object.peakRight)
        ? globalThis.Number(object.peakRight)
        : isSet(object.peak_right)
        ? globalThis.Number(object.peak_right)
        : 0,
    };
  },

  toJSON(message: TrackMeter): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.peakLeft !== 0) {
      obj.peakLeft = message.peakLeft;
    }
    if (message.peakRight !== 0) {
      obj.peakRight = message.peakRight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackMeter>, I>>(base?: I): TrackMeter {
    return TrackMeter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackMeter>, I>>(object: I): TrackMeter {
    const message = createBaseTrackMeter();
    message.trackId = object.trackId ?? "";
    message.peakLeft = object.peakLeft ?? 0;
    message.peakRight = object.peakRight ?? 0;
    return message;
  },
};

function createBaseMeters(): Meters {
  return { tracks: [], masterPeakLeft: 0, masterPeakRight: 0 };
}

export const Meters: MessageFns<Meters> = {
  encode(message: Meters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tracks) {
      TrackMeter.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.masterPeakLeft !== 0) {
      writer.uint32(21).float(message.masterPeakLeft);
    }
    if (message.masterPeakRight !== 0) {
      writer.uint32(29).float(message.masterPeakRight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Meters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMeters();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.tracks.push(TrackMeter.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.masterPeakLeft = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.masterPeakRight = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Meters {
    return {
      tracks: globalThis.Array.isArray(object?.tracks) ? object.tracks.map((e: any) => TrackMeter.fromJSON(e)) : [],
      masterPeakLeft: isSet(object.masterPeakLeft)
        ? globalThis.Number(object.masterPeakLeft)
        : isSet(object.master_peak_left)
        ? globalThis.Number(object.master_peak_left)
        : 0,
      masterPeakRight: isSet(object.masterPeakRight)
        ? globalThis.Number(object.masterPeakRight)
        : isSet(object.master_peak_right)
        ? globalThis.Number(object.master_peak_right)
        : 0,
    };
  },

  toJSON(message: Meters): unknown {
    const obj: any = {};
    if (message.tracks?.length) {
      obj.tracks = message.tracks.map((e) => TrackMeter.toJSON(e));
    }
    if (message.masterPeakLeft !== 0) {
      obj.masterPeakLeft = message.masterPeakLeft;
    }
    if (message.masterPeakRight !== 0) {
      obj.masterPeakRight = message.masterPeakRight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Meters>, I>>(base?: I): Meters {
    return Meters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Meters>, I>>(object: I): Meters {
    const message = createBaseMeters();
    message.tracks = object.tracks?.map((e) => TrackMeter.fromPartial(e)) || [];
    message.masterPeakLeft = object.masterPeakLeft ?? 0;
    message.masterPeakRight = object.masterPeakRight ?? 0;
    return message;
  },
};

function createBaseEngineState(): EngineState {
  return {
    bufferUnderruns: 0,
    cpuPercent: 0,
    latencySamples: 0,
    pluginBlocksMissed: 0,
    pluginChildAlive: false,
    pluginChildRestarts: 0,
  };
}

export const EngineState: MessageFns<EngineState> = {
  encode(message: EngineState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bufferUnderruns !== 0) {
      writer.uint32(8).uint64(message.bufferUnderruns);
    }
    if (message.cpuPercent !== 0) {
      writer.uint32(16).uint32(message.cpuPercent);
    }
    if (message.latencySamples !== 0) {
      writer.uint32(24).uint32(message.latencySamples);
    }
    if (message.pluginBlocksMissed !== 0) {
      writer.uint32(32).uint64(message.pluginBlocksMissed);
    }
    if (message.pluginChildAlive !== false) {
      writer.uint32(40).bool(message.pluginChildAlive);
    }
    if (message.pluginChildRestarts !== 0) {
      writer.uint32(48).uint32(message.pluginChildRestarts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EngineState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEngineState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.bufferUnderruns = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.cpuPercent = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.latencySamples = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.pluginBlocksMissed = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.pluginChildAlive = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.pluginChildRestarts = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): EngineState {
    return {
      bufferUnderruns: isSet(object.bufferUnderruns)
        ? globalThis.Number(object.bufferUnderruns)
        : isSet(object.buffer_underruns)
        ? globalThis.Number(object.buffer_underruns)
        : 0,
      cpuPercent: isSet(object.cpuPercent)
        ? globalThis.Number(object.cpuPercent)
        : isSet(object.cpu_percent)
        ? globalThis.Number(object.cpu_percent)
        : 0,
      latencySamples: isSet(object.latencySamples)
        ? globalThis.Number(object.latencySamples)
        : isSet(object.latency_samples)
        ? globalThis.Number(object.latency_samples)
        : 0,
      pluginBlocksMissed: isSet(object.pluginBlocksMissed)
        ? globalThis.Number(object.pluginBlocksMissed)
        : isSet(object.plugin_blocks_missed)
        ? globalThis.Number(object.plugin_blocks_missed)
        : 0,
      pluginChildAlive: isSet(object.pluginChildAlive)
        ? globalThis.Boolean(object.pluginChildAlive)
        : isSet(object.plugin_child_alive)
        ? globalThis.Boolean(object.plugin_child_alive)
        : false,
      pluginChildRestarts: isSet(object.pluginChildRestarts)
        ? globalThis.Number(object.pluginChildRestarts)
        : isSet(object.plugin_child_restarts)
        ? globalThis.Number(object.plugin_child_restarts)
        : 0,
    };
  },

  toJSON(message: EngineState): unknown {
    const obj: any = {};
    if (message.bufferUnderruns !== 0) {
      obj.bufferUnderruns = Math.round(message.bufferUnderruns);
    }
    if (message.cpuPercent !== 0) {
      obj.cpuPercent = Math.round(message.cpuPercent);
    }
    if (message.latencySamples !== 0) {
      obj.latencySamples = Math.round(message.latencySamples);
    }
    if (message.pluginBlocksMissed !== 0) {
      obj.pluginBlocksMissed = Math.round(message.pluginBlocksMissed);
    }
    if (message.pluginChildAlive !== false) {
      obj.pluginChildAlive = message.pluginChildAlive;
    }
    if (message.pluginChildRestarts !== 0) {
      obj.pluginChildRestarts = Math.round(message.pluginChildRestarts);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EngineState>, I>>(base?: I): EngineState {
    return EngineState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EngineState>, I>>(object: I): EngineState {
    const message = createBaseEngineState();
    message.bufferUnderruns = object.bufferUnderruns ?? 0;
    message.cpuPercent = object.cpuPercent ?? 0;
    message.latencySamples = object.latencySamples ?? 0;
    message.pluginBlocksMissed = object.pluginBlocksMissed ?? 0;
    message.pluginChildAlive = object.pluginChildAlive ?? false;
    message.pluginChildRestarts = object.pluginChildRestarts ?? 0;
    return message;
  },
};

function createBaseAudioTap(): AudioTap {
  return { firstSeq: 0, blockCount: 0, samples: new Uint8Array(0), droppedBlocks: 0 };
}

export const AudioTap: MessageFns<AudioTap> = {
  encode(message: AudioTap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstSeq !== 0) {
      writer.uint32(8).uint64(message.firstSeq);
    }
    if (message.blockCount !== 0) {
      writer.uint32(16).uint32(message.blockCount);
    }
    if (message.samples.length !== 0) {
      writer.uint32(26).bytes(message.samples);
    }
    if (message.droppedBlocks !== 0) {
      writer.uint32(32).uint64(message.droppedBlocks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioTap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAudioTap();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.firstSeq = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.blockCount = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.samples = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.droppedBlocks = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): AudioTap {
    return {
      firstSeq: isSet(object.firstSeq)
        ? globalThis.Number(object.firstSeq)
        : isSet(object.first_seq)
        ? globalThis.Number(object.first_seq)
        : 0,
      blockCount: isSet(object.blockCount)
        ? globalThis.Number(object.blockCount)
        : isSet(object.block_count)
        ? globalThis.Number(object.block_count)
        : 0,
      samples: isSet(object.samples) ? bytesFromBase64(object.samples) : new Uint8Array(0),
      droppedBlocks: isSet(object.droppedBlocks)
        ? globalThis.Number(object.droppedBlocks)
        : isSet(object.dropped_blocks)
        ? globalThis.Number(object.dropped_blocks)
        : 0,
    };
  },

  toJSON(message: AudioTap): unknown {
    const obj: any = {};
    if (message.firstSeq !== 0) {
      obj.firstSeq = Math.round(message.firstSeq);
    }
    if (message.blockCount !== 0) {
      obj.blockCount = Math.round(message.blockCount);
    }
    if (message.samples.length !== 0) {
      obj.samples = base64FromBytes(message.samples);
    }
    if (message.droppedBlocks !== 0) {
      obj.droppedBlocks = Math.round(message.droppedBlocks);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioTap>, I>>(base?: I): AudioTap {
    return AudioTap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioTap>, I>>(object: I): AudioTap {
    const message = createBaseAudioTap();
    message.firstSeq = object.firstSeq ?? 0;
    message.blockCount = object.blockCount ?? 0;
    message.samples = object.samples ?? new Uint8Array(0);
    message.droppedBlocks = object.droppedBlocks ?? 0;
    return message;
  },
};

function createBasePluginEntry(): PluginEntry {
  return { uid: "", name: "", vendor: "", subCategories: "" };
}

export const PluginEntry: MessageFns<PluginEntry> = {
  encode(message: PluginEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.vendor !== "") {
      writer.uint32(26).string(message.vendor);
    }
    if (message.subCategories !== "") {
      writer.uint32(34).string(message.subCategories);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePluginEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.uid = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.vendor = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.subCategories = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PluginEntry {
    return {
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      vendor: isSet(object.vendor) ? globalThis.String(object.vendor) : "",
      subCategories: isSet(object.subCategories)
        ? globalThis.String(object.subCategories)
        : isSet(object.sub_categories)
        ? globalThis.String(object.sub_categories)
        : "",
    };
  },

  toJSON(message: PluginEntry): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.vendor !== "") {
      obj.vendor = message.vendor;
    }
    if (message.subCategories !== "") {
      obj.subCategories = message.subCategories;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginEntry>, I>>(base?: I): PluginEntry {
    return PluginEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginEntry>, I>>(object: I): PluginEntry {
    const message = createBasePluginEntry();
    message.uid = object.uid ?? "";
    message.name = object.name ?? "";
    message.vendor = object.vendor ?? "";
    message.subCategories = object.subCategories ?? "";
    return message;
  },
};

function createBasePluginCatalog(): PluginCatalog {
  return { entries: [] };
}

export const PluginCatalog: MessageFns<PluginCatalog> = {
  encode(message: PluginCatalog, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      PluginEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginCatalog {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePluginCatalog();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.entries.push(PluginEntry.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PluginCatalog {
    return {
      entries: globalThis.Array.isArray(object?.entries) ? object.entries.map((e: any) => PluginEntry.fromJSON(e)) : [],
    };
  },

  toJSON(message: PluginCatalog): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => PluginEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginCatalog>, I>>(base?: I): PluginCatalog {
    return PluginCatalog.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginCatalog>, I>>(object: I): PluginCatalog {
    const message = createBasePluginCatalog();
    message.entries = object.entries?.map((e) => PluginEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseError(): Error {
  return { severity: 0, code: "", message: "" };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.severity !== 0) {
      writer.uint32(8).int32(message.severity);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseError();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.severity = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.message = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Error {
    return {
      severity: isSet(object.severity) ? error_SeverityFromJSON(object.severity) : 0,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.severity !== 0) {
      obj.severity = error_SeverityToJSON(message.severity);
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.severity = object.severity ?? 0;
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    transport: undefined,
    setMonitor: undefined,
    tapControl: undefined,
    position: undefined,
    meters: undefined,
    engineState: undefined,
    error: undefined,
    audioTap: undefined,
    pluginCatalog: undefined,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transport !== undefined) {
      TransportCommand.encode(message.transport, writer.uint32(10).fork()).join();
    }
    if (message.setMonitor !== undefined) {
      SetMonitor.encode(message.setMonitor, writer.uint32(18).fork()).join();
    }
    if (message.tapControl !== undefined) {
      TapControl.encode(message.tapControl, writer.uint32(58).fork()).join();
    }
    if (message.position !== undefined) {
      TransportPosition.encode(message.position, writer.uint32(26).fork()).join();
    }
    if (message.meters !== undefined) {
      Meters.encode(message.meters, writer.uint32(34).fork()).join();
    }
    if (message.engineState !== undefined) {
      EngineState.encode(message.engineState, writer.uint32(42).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(50).fork()).join();
    }
    if (message.audioTap !== undefined) {
      AudioTap.encode(message.audioTap, writer.uint32(66).fork()).join();
    }
    if (message.pluginCatalog !== undefined) {
      PluginCatalog.encode(message.pluginCatalog, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transport = TransportCommand.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.setMonitor = SetMonitor.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.tapControl = TapControl.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.position = TransportPosition.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.meters = Meters.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.engineState = EngineState.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.error = Error.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.audioTap = AudioTap.decode(reader, reader.uint32());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.pluginCatalog = PluginCatalog.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Message {
    return {
      transport: isSet(object.transport) ? TransportCommand.fromJSON(object.transport) : undefined,
      setMonitor: isSet(object.setMonitor)
        ? SetMonitor.fromJSON(object.setMonitor)
        : isSet(object.set_monitor)
        ? SetMonitor.fromJSON(object.set_monitor)
        : undefined,
      tapControl: isSet(object.tapControl)
        ? TapControl.fromJSON(object.tapControl)
        : isSet(object.tap_control)
        ? TapControl.fromJSON(object.tap_control)
        : undefined,
      position: isSet(object.position) ? TransportPosition.fromJSON(object.position) : undefined,
      meters: isSet(object.meters) ? Meters.fromJSON(object.meters) : undefined,
      engineState: isSet(object.engineState)
        ? EngineState.fromJSON(object.engineState)
        : isSet(object.engine_state)
        ? EngineState.fromJSON(object.engine_state)
        : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      audioTap: isSet(object.audioTap)
        ? AudioTap.fromJSON(object.audioTap)
        : isSet(object.audio_tap)
        ? AudioTap.fromJSON(object.audio_tap)
        : undefined,
      pluginCatalog: isSet(object.pluginCatalog)
        ? PluginCatalog.fromJSON(object.pluginCatalog)
        : isSet(object.plugin_catalog)
        ? PluginCatalog.fromJSON(object.plugin_catalog)
        : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.transport !== undefined) {
      obj.transport = TransportCommand.toJSON(message.transport);
    }
    if (message.setMonitor !== undefined) {
      obj.setMonitor = SetMonitor.toJSON(message.setMonitor);
    }
    if (message.tapControl !== undefined) {
      obj.tapControl = TapControl.toJSON(message.tapControl);
    }
    if (message.position !== undefined) {
      obj.position = TransportPosition.toJSON(message.position);
    }
    if (message.meters !== undefined) {
      obj.meters = Meters.toJSON(message.meters);
    }
    if (message.engineState !== undefined) {
      obj.engineState = EngineState.toJSON(message.engineState);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.audioTap !== undefined) {
      obj.audioTap = AudioTap.toJSON(message.audioTap);
    }
    if (message.pluginCatalog !== undefined) {
      obj.pluginCatalog = PluginCatalog.toJSON(message.pluginCatalog);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.transport = (object.transport !== undefined && object.transport !== null)
      ? TransportCommand.fromPartial(object.transport)
      : undefined;
    message.setMonitor = (object.setMonitor !== undefined && object.setMonitor !== null)
      ? SetMonitor.fromPartial(object.setMonitor)
      : undefined;
    message.tapControl = (object.tapControl !== undefined && object.tapControl !== null)
      ? TapControl.fromPartial(object.tapControl)
      : undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? TransportPosition.fromPartial(object.position)
      : undefined;
    message.meters = (object.meters !== undefined && object.meters !== null)
      ? Meters.fromPartial(object.meters)
      : undefined;
    message.engineState = (object.engineState !== undefined && object.engineState !== null)
      ? EngineState.fromPartial(object.engineState)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.audioTap = (object.audioTap !== undefined && object.audioTap !== null)
      ? AudioTap.fromPartial(object.audioTap)
      : undefined;
    message.pluginCatalog = (object.pluginCatalog !== undefined && object.pluginCatalog !== null)
      ? PluginCatalog.fromPartial(object.pluginCatalog)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
