// SPDX-License-Identifier: GPL-3.0-or-later
// A4-3: THE deterministic seed document, generated ONCE and vendored on
// every stage (web placeholder, Rust server default). All peers loading
// the SAME bytes share the same root change and object ids - offline
// edits made before first server contact merge cleanly instead of being
// wiped by a root conflict.
//
// NEVER regenerate casually: new bytes = a new root = the exact conflict
// this seed exists to prevent. Fixed actor, time 0, no message.
//
// Usage: node scripts/make-seed.mjs   (writes both artifacts, prints hash)

import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as Automerge from '@automerge/automerge';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, '..');
const repoRoot = resolve(webRoot, '..');

// Fixed actor: 16 bytes of hex, spells "da5eed" (the DAW seed)
let doc = Automerge.init({ actor: 'da5eed00da5eed00da5eed00da5eed00' });
doc = Automerge.change(doc, { time: 0 }, (d) => {
  d.schemaVersion = 1;
  d.sampleRate = 48000;
  d.tracks = [
    { id: 'track-1', name: 'Track 1', gain: 1, clips: [], chain: [] },
    { id: 'track-2', name: 'Track 2', gain: 0.75, clips: [], chain: [] },
  ];
});
const bytes = Automerge.save(doc);
const sha = createHash('sha256').update(bytes).digest('hex');

// 1. Rust: embedded via include_bytes! in websocket.rs
writeFileSync(join(repoRoot, 'server', 'src', 'document', 'seed.am'), bytes);

// 2. Web: base64 constant + loader
const b64 = Buffer.from(bytes).toString('base64');
const ts = `// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * A4-3: the deterministic SEED document - identical bytes on every
 * stage (server/src/document/seed.am is the same file). Generated by
 * scripts/make-seed.mjs; NEVER regenerate casually (new bytes = new
 * root = the offline-edit-wiping conflict this seed prevents).
 * sha256: ${sha}
 */
export const SEED_B64 = '${b64}';

export function seedBytes(): Uint8Array {
  const bin = atob(SEED_B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`;
writeFileSync(join(webRoot, 'src', 'document', 'seed.ts'), ts);
console.log(`seed: ${bytes.length} bytes, sha256 ${sha}`);
