// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * A4-3: the deterministic SEED document - identical bytes on every
 * stage (server/src/document/seed.am is the same file). Generated by
 * scripts/make-seed.mjs; NEVER regenerate casually (new bytes = new
 * root = the offline-edit-wiping conflict this seed prevents).
 * sha256: e0d16a34c4b75464a791e655ca760803f608912383e9f9918c97b650dcc83b21
 */
export const SEED_B64 = 'hW9KgxGdUo0AtQIBENpe7QDaXu0A2l7tANpe7QABH9aAtlwYbVoyVIV/PqQgGFpIXeUK2FLPDDNwSrVur/sGAQIDAhMCIwJAAlYCDAEEAggRBhMHFVYhAiMRNANCDlYQVymAAQJ/AH8Bfw9/AH8AfwcAAwwAAAMCAwUEBQoABH8AAAoAA34ABAAKfQpzYW1wbGVSYXRlDXNjaGVtYVZlcnNpb24GdHJhY2tzAAJ2BWNoYWluBWNsaXBzBGdhaW4CaWQEbmFtZQVjaGFpbgVjbGlwcwRnYWluAmlkBG5hbWUPAHsCfwIBBgN/fX4BCQJ/fn4BAwIKAgF/AgIAAgIDAQICAwF+NBQFAH8UAnYCAH+FAQJ2gPcCAQF0cmFjay0xVHJhY2sgMQAAAAAAAOg/dHJhY2stMlRyYWNrIDIPAAA=';

export function seedBytes(): Uint8Array {
  const bin = atob(SEED_B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
